stages:
  - test

variables:
  PLAYWRIGHT_BROWSERS_PATH: "0"

test:
  stage: test

  image: mcr.microsoft.com/playwright/java:v1.40.0-jammy

  script:
    - echo "Running Playwright tests..."
    - mvn clean test -Denv=qa