stages:
  - test

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  PLAYWRIGHT_BROWSERS_PATH: "0"
  ENV: "qa"
  HEADLESS: "true"

cache:
  paths:
    - .m2/repository

test:
  stage: test

  image: mcr.microsoft.com/playwright/java:v1.40.0-jammy

  script:
    - echo "Running tests on ENV=$ENV with HEADLESS=$HEADLESS"

    # 🔥 Run tests (Maven + Cucumber + Playwright)
    - mvn clean test -Denv=$ENV -Dheadless=$HEADLESS

    # 🔍 Debug
    - echo "=== TARGET CONTENT ==="
    - ls -R target || true

  artifacts:
    when: always
    paths:
      # 📦 Maven results
      - target/

      # 🧪 JUnit (GitLab test tab)
      - target/surefire-reports/

      # 🥒 CUCUMBER REPORTS
      - target/cucumber-reports/cucumber.html
      - target/cucumber-reports/cucumber.json

    expire_in: 7 days