name: Playwright Tests Multi-Env

on:
  push:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: [qa, dev, prod]

    env:
      PLAYWRIGHT_BROWSERS_PATH: 0

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Build project
        run: mvn clean install -DskipTests

      - name: Install Playwright
        run: mvn exec:java -Dexec.mainClass=com.microsoft.playwright.CLI -Dexec.args="install --with-deps"

      - name: Run tests on ${{ matrix.env }}
        run: mvn test -Denv=${{ matrix.env }}

      - name: Upload reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: reports-${{ matrix.env }}
          path: target/**